version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  server:
    build: ./server
    environment:
      - PORT=5000
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=dev_secret
      - MONGODB_URI=mongodb://mongo:27017/skillsync
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
volumes:
  mongo_data: